# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aesthetics Biomedical
email: sales@aestheticsbiomed.com
description: > # this means to ignore newlines until "baseurl:"
  Aesthetics Biomedical, Inc. is an aesthetic innovation company
  uniquely offering procedure and product enhancement, development,
  clinical indication expansion, application optimization, FDA
  clearance expertise, and worldwide distribution solutions for
  entrepreneurs, domestic, and international companies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aestheticsbiomed.com" # the base hostname & protocol for your site
twitter_username: aestheticsbm
facebook_username: aestheticsbiomed
youtube_username: UCmgQzTwO2dY6vrx9VadAMoQ
linkedin_username: aesthetics-biomed-inc
instagram_username: aestheticsbiomed
googleplus_username: 106690870889097201896

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/stylesheets

# stop Jekyll including your configuration in it’s generated site
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
gems:
  - jekyll-sitemap